### ISSUE TITLE
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open vectorstore/db_faiss/index.faiss for reading: No such file or directory

### ISSUE THREAD

**Issue by vishnumur777** [AIAnytime/Llama2-Medical-Chatbot#7]
Traceback (most recent call last):
  File "/home/hdd/MLProjects/yellow-paper-physics-bot/models.py", line 61, in <module>
    f=final_result("Define Weight")
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdd/MLProjects/yellow-paper-physics-bot/models.py", line 57, in final_result
    qa_result = qa_bot()
                ^^^^^^^^
  File "/home/hdd/MLProjects/yellow-paper-physics-bot/models.py", line 49, in qa_bot
    db = FAISS.load_local(DB_FAISS_PATH, embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/varun/.local/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 696, in load_local
    index = faiss.read_index(
            ^^^^^^^^^^^^^^^^^
  File "/home/varun/.local/lib/python3.11/site-packages/faiss/swigfaiss_avx2.py", line 10206, in read_index
    return _swigfaiss_avx2.read_index(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open vectorstore/db_faiss/index.faiss for reading: No such file or directory

**Comment by owencraston** [comment]
I am also getting this error

**Comment by ashusnapx** [comment]
you might've mistaken the name of vectorstore as vectorstores, just check it. Close this issue, if your issue is resolved.

**Comment by vishnumur777** [comment]
Yep! the issue resolved!!!
