### ISSUE TITLE
Could not import ctransformers package.

### ISSUE THREAD

**Issue by owencraston** [AIAnytime/Llama2-Medical-Chatbot#8]
I am trying to run this project on a Macbook pro m1 and am getting the following stacktrace. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/chainlit/utils.py", line 36, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owencraston/src/personal/ai/demo/model.py", line 79, in start
    chain = qa_bot()
            ^^^^^^^^
  File "/Users/owencraston/src/personal/ai/demo/model.py", line 62, in qa_bot
    llm = load_llm()
          ^^^^^^^^^^
  File "/Users/owencraston/src/personal/ai/demo/model.py", line 46, in load_llm
    llm = CTransformers(
          ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/usr/local/lib/python3.11/site-packages/langchain/llms/ctransformers.py", line 67, in validate_environment
    raise ImportError(
ImportError: Could not import `ctransformers` package. Please install it with `pip install ctransformers`
```

I have of course ran `pip install ctransformers`

I am also using python 3.11. Does anyone know what the issue could be?

**Comment by oqp** [comment]
Did you solve this? I have the same error but I'm using conda not pip

**Comment by ashusnapx** [comment]
rather than conda make a environment using python, in vs code or your IDE, and then run `pip install ctransformers`.
Thanks and close this issue.

**Comment by oqp** [comment]
Thanks, but I'm using GPU and with pip is not possible to use Cuda.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ezyweb-uk** [comment]
I had the same error. I think I had installed 'transformers' as listed in the requirements. Once I had installed '**c**transformers' the error disappeared.

**Comment by tahairshad** [comment]
pip install langchain_community
